name: Build

on:
  push:
    branches:
      - main  # Run on push to the main branch (or change as needed)

jobs:
  sonarqube:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest  # Switch to Linux runner for faster execution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
