name: Build

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the build on (adjust as necessary)

jobs:
  sonarqube:
    name: Run SonarQube analysis
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version
        with:
          fetch-depth: 0  # Ensures you get the full git history

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v2  # It's better to use a stable release rather than 'master'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure your token is in GitHub secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Ensure this has the full URL (http:// or https://)
